package customerio

import "context"

// SenderIdentity is a from-address configuration usable when sending
// campaigns/broadcasts/newsletters/transactional messages.
type SenderIdentity struct {
	ID            int    `json:"id"`
	DeduplicateID string `json:"deduplicate_id,omitempty"`
	Name          string `json:"name,omitempty"`
	Email         string `json:"email,omitempty"`
	Address       string `json:"address,omitempty"`
	TemplateType  string `json:"template_type,omitempty"`
	AutoGenerated bool   `json:"auto_generated,omitempty"`
	Phone         string `json:"phone,omitempty"`
	Hidden        bool   `json:"hidden,omitempty"`
}

// SenderIdentitiesOptions filters/sorts/paginates GetSenderIdentities.
type SenderIdentitiesOptions struct {
	PaginationOptions
	Sort   SortDirection
	Hidden *bool
}

// ListSenderIdentitiesResponse is the decoded shape of GET /v1/sender_identities.
type ListSenderIdentitiesResponse struct {
	SenderIdentities []SenderIdentity `json:"sender_identities"`
}

// GetSenderIdentities returns every sender identity configured in the workspace.
// See https://docs.customer.io/api/app/#operation/getSenderIdentities
func (c *APIClient) GetSenderIdentities(ctx context.Context, opts SenderIdentitiesOptions) (*ListSenderIdentitiesResponse, error) {
	q := opts.PaginationOptions.apply(newQuery()).setString("sort", string(opts.Sort)).setBool("hidden", opts.Hidden)
	requestPath := "/v1/sender_identities" + q.String()

	var resp ListSenderIdentitiesResponse
	if err := c.doJSON(ctx, "GET", requestPath, nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SenderIdentityResponse wraps a single SenderIdentity.
type SenderIdentityResponse struct {
	SenderIdentity SenderIdentity `json:"sender_identity"`
}

// GetSenderIdentity returns one sender identity by id.
// See https://docs.customer.io/api/app/#operation/getSenderIdentity
func (c *APIClient) GetSenderIdentity(ctx context.Context, senderID string) (*SenderIdentityResponse, error) {
	if senderID == "" {
		return nil, ParamError{Param: "senderID"}
	}

	var resp SenderIdentityResponse
	if err := c.doJSON(ctx, "GET", formatPath("/v1/sender_identities/%s", senderID), nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

// SenderIdentityUsedByResponse is the decoded shape of
// GET /v1/sender_identities/{id}/used_by. The per-resource-type shape of
// UsedBy isn't documented anywhere in the App API's published reference —
// unlike GetSegmentUsedBy, which does document its used_by fields — so it's
// left as a generic map rather than guessed.
type SenderIdentityUsedByResponse struct {
	SenderID int            `json:"sender_id,omitempty"`
	UsedBy   map[string]any `json:"used_by,omitempty"`
}

// GetSenderIdentityUsedBy returns what campaigns/broadcasts/newsletters/etc.
// reference a sender identity — useful to check before hiding/deleting it.
// See https://docs.customer.io/api/app/#operation/getSenderIdentityUsedBy
func (c *APIClient) GetSenderIdentityUsedBy(ctx context.Context, senderID string) (*SenderIdentityUsedByResponse, error) {
	if senderID == "" {
		return nil, ParamError{Param: "senderID"}
	}

	var resp SenderIdentityUsedByResponse
	if err := c.doJSON(ctx, "GET", formatPath("/v1/sender_identities/%s/used_by", senderID), nil, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
